// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iycdadjtgmjwdumuasyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y2RhZGp0Z21qd2R1bXVhc3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTI4MDQsImV4cCI6MjA2MDA4ODgwNH0.SOoAl2REbLrfP4tCYDmwrE8Ve5OLkE4VmpEWJ_IDY8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);